spring.application.name=shop

# 템플릿 경로 설정 (기본값: templates)
spring.thymeleaf.prefix=classpath:/templates/
# 템플릿 확장자 설정 (기본값: .html)
spring.thymeleaf.suffix=.html
# 템플릿 모드 설정 (기본값: HTML)
spring.thymeleaf.mode=HTML
# 인코딩 설정 (기본값: UTF-8)
spring.thymeleaf.encoding=UTF-8

# 개발 환경: 캐시 사용 안 함 (수정 시 바로 반영)
spring.thymeleaf.cache=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.url=gateway01.ap-northeast-1.prod.aws.tidbcloud.com
spring.datasource.username=2LWWjfNKzLYhGfs.root
spring.datasource.password=bcDaU03rHZEEmblq
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect